apiVersion: v1
kind: Service
metadata:
  name: idp-hj-backend
  namespace: ops-system
  labels:
    app: idp-hj-backend
spec:
  selector:
    app: idp-hj-backend
  ports:
    - port: 80
      targetPort: 3030
      protocol: TCP
  type: ClusterIP
