apiVersion: batch/v1
kind: CronJob
metadata:
  name: k8s-resource-optimizer
  namespace: ops-system
spec:
  schedule: "*/1 * * * *"
  timeZone: Asia/Seoul
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app.kubernetes.io/name: k8s-resource-optimizer
            application: k8s-resource-optimizer
        spec:
          restartPolicy: OnFailure
          containers:
            - name: k8s-resource-optimizer
              image: docconman/k8s-resource-optimizer:latest
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - "-c"
                - "python3 run_recommender.py --n $NAMESPACE"
              env:
                - name: NAMESPACE
                  value: 'argocd'
                - name: SLACK_CHANNEL
                  valueFrom:
                    configMapKeyRef:
                      name: k8s-resource-optimizer-cm
                      key: SLACK_CHANNEL
                - name: PROMETHEUS_URL
                  valueFrom:
                    configMapKeyRef:
                      name: k8s-resource-optimizer-cm
                      key: PROMETHEUS_URL
                - name: SLACK_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: k8s-resource-optimizer-sc
                      key: SLACK_TOKEN
                # - name: SLACK_TOKEN
                #   valueFrom:
                #     configMapKeyRef:
                #       name: k8s-resource-optimizer-cm
                #       key: SLACK_TOKEN
              # resources:
              #   requests:
              #     memory: '200Mi'
              #   limits:
              #     memory: '200Mi'

