export const ENV_PROTOCOL_KEY='PROTOCOL';
export const ENV_JENKINS_URL_KEY='JENKINS_URL';
export const ENV_JENKINS_USER_KEY='JENKINS_USER';
export const ENV_JENKINS_API_TOKEN_KEY='JENKINS_API_TOKEN';

export const ENV_ARGOCD_URL_KEY='ARGOCD_URL';
export const ENV_ARGOCD_API_TOKEN_KEY='ARGOCD_API_TOKEN';
