apiVersion: v1
kind: Service
metadata:
  name: idp-hj-frontend
  namespace: ops-system
  labels:
    app: idp-hj-frontend
spec:
  selector:
    app: idp-hj-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
