apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatbot-data
  namespace: ops-system
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: standard
  resources:
    requests:
      storage: 10Gi