apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chatbot
  namespace: ops-system
  labels:
    app: chatbot
spec:
  serviceName: "chatbot"
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: docconman/hj-chatbot:latest
        ports:
        - containerPort: 5000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: chatbot-sc
              key: OPENAI_API_KEY
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            memory: "256Mi"
        volumeMounts:
        - name: data
          mountPath: /app/data
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: chatbot-data
