services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80"
    environment:
      REACT_APP_BACKEND_URL: http://backend:3030
    depends_on:
      - backend
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3030:3030"
    environment:
      PROTOCOL: http
      JENKINS_URL:
      JENKINS_USER:
      JENKINS_API_TOKEN:
      ARGOCD_URL:
      ARGOCD_USER:
      ARGOCD_API_TOKEN:
      DEMO_MODE: true